### ISSUE TITLE
python cannot load modules in 'scripts'

### ISSUE THREAD

**Issue by clemgoub** [LiLabAtVT/DeepTE#2]
Hello!

I am very excited on trying DeepTE. However I am encountering what seem to be a simple Python error:

```
Traceback (most recent call last):
  File "./DeepTE.py", line 16, in <module>
    from scripts import DeepTE_pipeline_no_modification as pipeline_no_m
ImportError: cannot import name 'DeepTE_pipeline_no_modification'
```

how can I fix this module import issue?

Many thanks,

Clément

**Comment by yanhaidong1** [comment]
> Hello!
> 
> I am very excited on trying DeepTE. However I am encountering what seem to be a simple Python error:
> 
> ```
> Traceback (most recent call last):
>   File "./DeepTE.py", line 16, in <module>
>     from scripts import DeepTE_pipeline_no_modification as pipeline_no_m
> ImportError: cannot import name 'DeepTE_pipeline_no_modification'
> ```
> 
> how can I fix this module import issue?
> 
> Many thanks,
> 
> Clément



> Hello!
> 
> I am very excited on trying DeepTE. However I am encountering what seem to be a simple Python error:
> 
> ```
> Traceback (most recent call last):
>   File "./DeepTE.py", line 16, in <module>
>     from scripts import DeepTE_pipeline_no_modification as pipeline_no_m
> ImportError: cannot import name 'DeepTE_pipeline_no_modification'
> ```
> 
> how can I fix this module import issue?
> 
> Many thanks,
> 
> Clément

Dear Clément, 

I am glad and excited you are trying DeepTE. 
I am thinking you put the DeepTE.py to a folder that does not contain scripts directory.
Can you try to put them together and run the DeepTE.py? 
Please tell me whether it works or not.

Thanks
Best wishes
Haidong

**Comment by clemgoub** [comment]
Hello Haidong,

Thank you for your fast response. I looked at this and the file `DeepTE.py` is in the folder containing the `scripts/` directory with the expected files.

I am using Python3.6 but I am currently reinstalling all the python deps from conda. I will keep you updated.

Many thanks,

Clément

**Comment by yanhaidong1** [comment]
> Hello Haidong,
> 
> Thank you for your fast response. I looked at this and the file `DeepTE.py` is in the folder containing the `scripts/` directory with the expected files.
> 
> I am using Python3.6 but I am currently reinstalling all the python deps from conda. I will keep you updated.
> 
> Many thanks,
> 
> Clément

Dear Clément,
Awesome. Please let me known if you have issues with DeepTE.
Best wishes
Haidong

**Comment by clemgoub** [comment]
Hi Haidong,

I figured out my issue. I was running DeepTE.py using the `python DeepTE.py` command instead of `DeepTE.py`

It is working well and fast, I am very impressed. I will benchmark it in a lot of insects. What is the representation in species and sequences of the training set for Metazoans? (I guess I'll have to go back to the paper =) )

Cheers,

Clément
