### ISSUE TITLE
Can not perform DeepTE

### ISSUE THREAD

**Issue by bilibilij** [LiLabAtVT/DeepTE#5]
![DEEPTE](https://user-images.githubusercontent.com/49976278/88888604-3628c380-d271-11ea-976f-e9e732a99d9e.png)
I would like to use DeepTE to annotate my genome.  
I have followed the Maual.pdf to prepare the Prerequisites of DeepTE software. But when I try to perform DeepTE with command"  python DeepTE.py -d /w/00/g/g00/changfu/v2.2/v2.2/fasta/DeepTE_test/working_dir -o /w/00/g/g00/changfu/v2.2/v2.2/fasta/DeepTE_test/output_dir -i /w/00/g/g00/changfu/v2.2/v2.2/fasta/DeepTE_test/repeatmodeler.lib -sp plant -m_dir /w/00/g/g00/changfu/miniconda/envs/py36/share/Plants_model "
, the Keyerror '1 ' often print at last .
What should I do for performing DeepTE in normal ?

**Comment by yanhaidong1** [comment]
Thanks for using the DeepTE.
I am thinking you need to use the '-sp P' instead of '-sp plant' in this command line.
Best,
Haidong

**Comment by bilibilij** [comment]
Thank you for your reply and now I could run DeepTE with your recommendation.

**Comment by yanhaidong1** [comment]
Hi, I glad you can run. If you have any question, please let me know. Thanks!
